irc:
  server: 'localhost'
  port: 12345
  channels: []
  user: 'inori'
  nick: 'Inori'

mumble:
  username: Inori
  password: ''
  address: 'localhost'
  port: 64738
  triggers: ['mumblecop', 'mc', 'mb']
  comment: :text
  comment_text: 'I am a robot beep boop'
  initial-volume: 5
  use-mpd: true
  fifo-pipe-location: '/tmp/mpd_fifo'
  mpd-port: 6600
  mpd-address: localhost
  plugin-update-rate: 0.5
  default-plugin-condition: :all
  verbose-chat-log: false
  multithread-commands: true
  mpd-callbacks: true
  debug: false
  trusted-users-file: 'trusted-users.txt'
  blacklisted-users-file: 'blacklisted-users.txt'
  plugins:
    volume:
      min_volume: 5
